# [window]
# decorations = "Transparent"
# blur = true
# # opacity = 0.7
# startup_mode = "Maximized"
#
#
# title = "ROMANVIKI"
# decorations_theme_variant = "Dark"
#
#
# [font]
# # normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = {family = "FiraCode Nerd Font",style='Regular'}
# bold = {family="FiraCode Nerd Font", style="Bold"}
# italic = {family="FiraCode Nerd Font", style="italic"}
#
#
# [env]
# TERM = "xterm-256color"
#
# [keyboard]
# bindings = [
#     { key = "F11", action = "ToggleFullscreen" },
# {key = "F2", action = "ToggleViMode"}
# ]

# Alacritty Configuration (TOML Format)

[window]
decorations = "Transparent"  # Makes window decorations transparent
blur = true  # Enables blur effect
# opacity = 0.7  # You can uncomment this to adjust the transparency opacity (value from 0 to 1)
startup_mode = "Maximized"  # Starts the terminal in maximized mode

title = "ROMANVIKI"  # Title for the terminal window
decorations_theme_variant = "Dark"  # Dark theme for window decorations

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }  # Setting FiraCode Nerd Font as the default font
size = 10.0
# bold = { family = "FiraCode Nerd Font", style = "Bold" }  # Bold font setting
# italic = { family = "FiraCode Nerd Font", style = "Italic" }  # Italic font setting

[env]
TERM = "xterm-256color"  # 256 color terminal for compatibility

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },  # F11 for fullscreen toggle
    { key = "E", mods="Alt", action = "ToggleViMode" }  # F2 for toggling Vi mode
]

# Colors and other customizations
# Below we add custom colors to make it more aesthetically pleasing.

# Custom Cursor Style (optional)
[cursor]
  style = "Block"  # Set cursor to block style

# This is an optional section for setting up a shell prompt arrow (in your shell config like bash or zsh)
# In ~/.bashrc or ~/.zshrc, set your prompt like this:
# PS1='→ '


